table customer_features {
    column customer_id dataType: string { isKey: true }
    column name dataType: string
    column age dataType: int64
    column gender dataType: string
    column city dataType: string
    column latitude dataType: double
    column longitude dataType: double
    column phone dataType: int64
    column email dataType: string
    column signup_date dataType: string
    column is_active dataType: boolean { trueValue: "True", falseValue: "False" }
    column recency_days dataType: double
    column frequency dataType: double
    column monetary dataType: double
    column avg_order_value dataType: double
    column avg_discount_used dataType: double
    column preferred_payment dataType: string
    column cuisine_variety dataType: double
    column first_order_date dataType: string
    column last_order_date dataType: string
    column days_since_first dataType: double
    column customer_segment dataType: string
    column customer_tenure_months dataType: double
    column avg_order_frequency_days dataType: double

    partition 'Partition' mode: import { source: #"customer_features" }

    measure 'Customer Segment Count' := DISTINCTCOUNT(customer_features[customer_segment])
}