table delivery_logs {
    column delivery_id dataType: string { isKey: true }
    column order_id dataType: string
    column driver_id dataType: string
    column pickup_datetime dataType: string
    column drop_datetime dataType: string
    column distance_km dataType: double
    column travel_time_mins dataType: int64
    column traffic_condition dataType: string
    column weather_condition dataType: string
    column is_on_time dataType: boolean { trueValue: "True", falseValue: "False" }

    partition 'Partition' mode: import { source: #"delivery_logs" }

    measure 'OnTime Delivery Rate' := VAR TotalDeliveries = COUNTROWS(delivery_logs) VAR OnTime = COUNTROWS(FILTER(delivery_logs, delivery_logs[is_on_time] = TRUE)) RETURN DIVIDE(OnTime, TotalDeliveries, 0)
    measure 'Avg Delivery Time Mins' := AVERAGE(delivery_logs[travel_time_mins])
    measure 'Avg Delivery Distance KM' := AVERAGE(delivery_logs[distance_km])
}