table restaurants {
    column restaurant_id dataType: string { isKey: true }
    column name dataType: string
    column cuisine_type dataType: string
    column city dataType: string
    column latitude dataType: double
    column longitude dataType: double
    column rating dataType: double
    column avg_cost_for_two dataType: int64
    column join_date dataType: string
    column is_active dataType: boolean { trueValue: "True", falseValue: "False" }
    column preparation_time_mins dataType: int64

    partition 'Partition' mode: import { source: #"restaurants" }

    measure 'Active Restaurants' := CALCULATE(COUNTROWS(restaurants), restaurants[is_active] = TRUE)
}